///
/// @Generated by Mockolo
///



import Foundation
import RxCocoa
import RxSwift
@testable import RxTestSample


class CardProtocolMock: CardProtocol {
    init() { }
    init(brand: String = "", number: String = "") {
        self.brand = brand
        self.number = number
    }


    private(set) var brandSetCallCount = 0
    var brand: String = "" { didSet { brandSetCallCount += 1 } }

    private(set) var numberSetCallCount = 0
    var number: String = "" { didSet { numberSetCallCount += 1 } }
}

class UseCaseProtocolMock: UseCaseProtocol {
    init() { }
    init(repository: RepositoryProtocol!) {
        self._repository = repository
    }


    private(set) var repositorySetCallCount = 0
    private var _repository: RepositoryProtocol!  { didSet { repositorySetCallCount += 1 } }
    var repository: RepositoryProtocol! {
        get { return _repository }
        set { _repository = newValue }
    }

    private(set) var executeCallCount = 0
    var executeHandler: (() -> (Single<CardProtocol>))?
    func execute() -> Single<CardProtocol> {
        executeCallCount += 1
        if let executeHandler = executeHandler {
            return executeHandler()
        }
        fatalError("executeHandler returns can't have a default value thus its handler must be set")
    }
}

